"""work on name model

Revision ID: 05b510fdacdd
Revises: 6ecebb1f2d3a
Create Date: 2024-11-03 13:33:47.581487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05b510fdacdd'
down_revision = '6ecebb1f2d3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
