"""Add all

Revision ID: 7311bbd6ae23
Revises: 050d0639d280
Create Date: 2024-11-03 12:42:07.041919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7311bbd6ae23'
down_revision = '050d0639d280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
