"""change create_date

Revision ID: 79be48908072
Revises: 7311bbd6ae23
Create Date: 2024-11-03 13:06:17.113310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79be48908072'
down_revision = '7311bbd6ae23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
