"""add pre-model

Revision ID: f7e2861080e7
Revises: 0f956e500ad9
Create Date: 2024-11-02 11:20:11.199360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7e2861080e7'
down_revision = '0f956e500ad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
